### ISSUE TITLE
`.github/` should be excluded by default

### ISSUE THREAD

**Issue by jakewrfoster** [alleyinteractive/action-deploy-to-remote-repository#12]
### Description

the .github folders should be excluded by default from the deploys.

### Use Case

when a deploy pipline uses the default configuration, it shouldn't pass along the .github folders that are used by the source repos.

**Comment by jakewrfoster** [comment]
@anubisthejackle can you add details about the completion of this issue here (eg PR, comments, etc)?

**Comment by anubisthejackle** [comment]
This was completed in #11. The `.github` directory should be excluded now from the rsync. However, because `exclude` also excludes the same directory from _deletion_ any files that have already made their way to VIP repositories will need to be manually removed.
