### ISSUE TITLE
Don't Sync mu-plugins/pantheon-mu-plugin

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/action-deploy-to-remote-repository#6]
### Description of the bug

Pantheon maintains a copy of mu-plugins/pantheon-mu-plugin in the upstream, and installing it locally (or removing it from wp-content) causes an error when updating from the upstream in Pantheon. We should ignore it when running the rsync so that Pantheon can maintain their copy of that directory.

### Steps To Reproduce

1. `composer require pantheon-systems/pantheon-mu-plugin` in a wp-content rooted project such that the pantheon-mu-plugin folder is installed to `mu-plugins/pantheon-mu-plugin`.
2. Deploy the change to a Pantheon environment.
3. Attempt to apply upstream updates (e.g., a WordPress update) and observe that it fails (do this via Terminus to get the exact reason, which is a merge conflict in the mu-plugin related to deleting the .gitignore file, which is apparently present in the upstream that pulls from their git repo but not in the Packagist-managed Composer-installed version).

**Comment by benpbolton** [comment]
This already _seems_ possible by modifying the action's "exclude list" (more info [here](https://github.com/alleyinteractive/action-deploy-to-remote-repository?tab=readme-ov-file#exclude_list)) ... would adding `pantheon-mu-plugin` to the exclude list fit the use-case here?

**Comment by kevinfodness** [comment]
It could, but it would be incumbent upon all users of this action to know to include that property. We already have a `pantheon` boolean which configures certain behavior automatically, and I'd recommend adding this plugin to the exclude list automatically if the pantheon flag is set to true, and updating the documentation accordingly. That way, users could simply specify that they're deploying to Pantheon and have it automatically ignore any local copies of Pantheon's mu-plugin.
